version: '2'
services:
    jhtest9-app:
        image: jhtest9
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhtest9-mysql:3306/jhtest9?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhtest9-mysql:
        extends:
            file: mysql.yml
            service: jhtest9-mysql
